---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Une hije tiene muchas madres.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Une (y quizás varies) hije/s tiene/n una madre.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Una madre tiene muchos hijes.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Muchas madres tienen une misme hije.
  checked: false
name: Madre hay una sola
