---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ponemos el nombre del disco en un campo de la canci칩n
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ponemos el id del disco en un campo de la canci칩n
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ponemos el id de la canci칩n en un campo del 치lbum
  checked: false
name: Disco de oro
